tutorial/blog/urls.py
from blog.views.blog_search import BlogSearchView
from blog.views.chat import ChatView
from blog.views.examplereflex import ExamplereflexView
from blog.views.examplereflex_with_js import ExamplereflexWithJsView
from blog.views.signup import SignupView
from blog.views.views import PostDetailView, PostListView, SearchResultView
from django.conf.urls import url
from django.urls import path

app_name = "blog"

urlpatterns = [
    url(r"^$", PostListView.as_view(), name="post_list"),
    url(
        r"^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$",
        PostDetailView.as_view(),
        name="post_detail",
    ),
    path("search/", SearchResultView.as_view(), name="search_result"),
    path("example-reflex/", ExamplereflexView.as_view(), name="example_reflex"),
    path(
        "example-reflex-js/",
        ExamplereflexWithJsView.as_view(),
        name="example_reflex_js",
    ),
    path("chat-reflex/", ChatView.as_view(), name="chat_reflex"),
    path("signup-reflex/", SignupView.as_view(), name="signup_reflex"),
    path("blog-search-reflex/", BlogSearchView.as_view(), name="blog_search_reflex"),
]

tutorial/tutorial/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path(r"comments/", include("django_comments_xtd.urls")),
    path(r"admin/", admin.site.urls),
    path(r"blog/", include("blog.urls", namespace="blog")),
    path(r"", TemplateView.as_view(template_name="home.html"), name="homepage"),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/blog/models.py
# from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class PublicManager(models.Manager):
    def get_queryset(self):
        return (
            super(PublicManager, self)
            .get_queryset()
            .filter(publish__lte=timezone.now())
        )


class Post(models.Model):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    body = models.TextField()
    allow_comments = models.BooleanField("allow comments", default=True)
    publish = models.DateTimeField(default=timezone.now)
    objects = PublicManager()  # Our custom manager.

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            kwargs={
                "year": self.publish.year,
                "month": self.publish.strftime("%b"),
                "day": self.publish.strftime("%d"),
                "slug": self.slug,
            },
        )


class Subscription(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=256)

tutorial/blog/views/blog_search.py
from django.views.generic.base import TemplateView


class BlogSearchView(TemplateView):
    template_name = "blog/blog_search.html"
    subtitle = None

tutorial/blog/views/chat.py
from django.core.cache import cache
from django.views.generic.base import TemplateView


class ChatView(TemplateView):
    subtitle = "Chat"
    template_name = "blog/chat.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["chats"] = cache.get("chats", [])
        return context

tutorial/blog/views/examplereflex.py
from django.views.generic.base import TemplateView


class ExamplereflexView(TemplateView):
    template_name = "blog/examplereflex.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["count"] = 0
        return context

tutorial/blog/views/examplereflex_with_js.py
from django.views.generic.base import TemplateView


class ExamplereflexWithJsView(TemplateView):
    template_name = "blog/examplereflex_with_js.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["count"] = 0
        return context

tutorial/blog/views/mixins.py
# import os
# from collections import defaultdict

from django.conf import settings

BASE_PATH = settings.BASE_DIR


class BookSearchMixin:
    template_name = "blog/book_search_reflex.html"
    subtitle = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["some_data"] = "placeholder_string"
        return context

tutorial/blog/views/signup.py
from blog.models import Subscription
from django.forms import ModelForm
from django.views.generic.edit import FormView


class SubscriptionForm(ModelForm):
    class Meta:
        model = Subscription
        fields = ["name", "email"]


class SignupView(FormView):
    template_name = "blog/signup.html"
    form_class = SubscriptionForm
    subtitle = "Newsletter Signup"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["people"] = Subscription.objects.all()
        return context

tutorial/blog/views/views.py
import random
import time

# use this import instead of short 'from .models' to escape RuntimeErros
# https://medium.com/@michal.bock/fix-weird-exceptions-when-running-django-tests-f58def71b59a
from blog.models import Post
from django.db.models import Q
from django.views.generic import DetailView, ListView  # ,TemplateView


class PostListView(ListView):
    model = Post
    context_object_name = "post_list"
    template_name = "blog/post_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Added to see blue wait bar on top, as indication of working turbolinks
        time.sleep(random.randint(2, 3))
        return context


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "blog/post_detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # default value for 'cid'
        context["cid"] = 0
        return context


class SearchResultView(ListView):
    model = Post
    context_object_name = "post_list"
    template_name = "blog/search_results.html"
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Post.objects.filter(
            Q(title__icontains=query) | Q(title__icontains=query)
        )

tutorial/templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}django-comments-xtd tutorial{% endblock %}</title>

    <!-- Bootstrap CSS for django-comments-xtd styling -->
    <link href="{% static 'css/bootstrap-4.3.1.min.css' %}" rel="stylesheet">

    <!-- Bootstrap CSS from bootswatch styling -->
    <link href="{% static 'css/bootstrap.lumen.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Fontawesome CSS -->
    <link href="{% static 'css/all.css' %}" rel="stylesheet">

    <!-- Custom CSS for project,it was build with webpack -->
    <link href="{% static 'app.css' %}" rel="stylesheet">
 
    <!-- Third-party javascript libraries -->
    <script defer src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script defer src="{% static 'js/popper.min.js' %}"></script>
    <script defer src="{% static 'js/bootstrap.min.js' %}"></script>
    <script defer src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script defer src="{% static 'js/prism.js' %}"></script>

    <!-- Webpack build combination of all project .js files -->
    <script type="module" src="{% static 'app.js' %}"></script>
    
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarColor03">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'homepage' %}">Home
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:post_list' %}">Posts</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><strong>REFLEXES</strong></a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'blog:example_reflex' %}">Count Reflex</a>
                <a class="dropdown-item" href="{% url 'blog:example_reflex_js' %}">Count Reflex Js</a>
                <a class="dropdown-item" href="{% url 'blog:chat_reflex' %}">Chat Reflex</a>
                <a class="dropdown-item" href="{% url 'blog:signup_reflex' %}">Signup Reflex</a>
                <a class="dropdown-item" href="{% url 'blog:blog_search_reflex' %}">Posts Search Reflex</a>
              </div>
            </li>
          </ul>
          <form class="d-flex" action="{% url 'blog:search_result' %}" method="get">
            <input name="q" class="form-control me-sm-2" type="text" placeholder="Regular Django search...">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row my-4">
        <div class="col-lg-12">
	      <h5 class="text-center">django-sockpuppet-example</h5>
          <hr/>
        </div>
      </div>
    </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <hr/>
          <p class="text-center text-muted small">django-sockpuppet-example.</p>
        </div>
      </div>
    </div>

    {% block extra-js %}
    {% endblock %}
  </body>
</html>

tutorial/templates/blog/blog_search.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block subtitle %}{{ subtitle }}{% endblock subtitle %}

{% block content %}
  <div class="row justify-content-center flex-fill">
    <div class="col-md-10">
      <p class="lead">These are results of search with <code>Reflexes</code> functionality.</p>
      <p class="lead">Type in to see its <strong>reactive</strong>.</p>
    </div>
  </div>
  <div class="container">
    <form data-controller="blog_search" data-reflex-root="#morph" class="">
      <input type="text" placeholder="search for a post ..." data-target="blog_search.query"
        data-action="debounced:input->blog_search#perform" class="form-control"/>
      <div id="morph">
        <div>
          <span data-target="blog_search.activity" class="" hidden>
            <i class="fas fa-spinner fa-spin"></i>
            Searching for posts...
          </span>
          <span data-target="blog_search.count" class="">
            <strong>{{count|default:0|intcomma}}</strong> posts found
          </span>
        </div>
        <table data-target="blog_search.list" {% if  not posts %} hidden {% endif %}>
          <thead>
            <tr>
              <th scope="col">Post</th>
              <th scope="col">Primary Key</th>
              <th scope="col">Date</th>
              <th scope="col">Author</th>
            </tr>
          </thead>
          <tbody>
            {% for post in posts|slice:'0:5'  %}
            <tr>
              <th scope="row"><h3><a class="nounderline" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3></th>
              <td>{{ post.pk }}</td>
              <td>{{ post.publish }}</td>
              <td>Anonymos</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </form>
  </div>
{% endblock %}

tutorial/templates/blog/chat.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block subtitle %}{{ subtitle }}{% endblock subtitle %}

{% block content %}
<h3 class="lead"> This <code>Reflex</code> implements <strong>Chat</strong> functionality in application.</h3>
<article id="red"
    data-controller="chat"
    data-action="chats:added@document->chat#reload cable-ready:after-morph@document->chat#scroll"
    data-reflex-root="#chat-container"
    >
    <div class="card" id="chat-container" data-target="chat.list">
      <h4 class="card-header bg-info">MESSAGES: {{chats|length}} </h4>
      <div class="card-body">
      {% for chat in chats  %}
        <aside class="message" style="min-height:auto; margin-top: 15px;">
          <h6 class="card-title">
          {{ chat.message }} <sup> <span class="badge bg-dark"> {{ chat.created_at|timesince }} ago  </span></sup>
          </h6>
        </aside>
      {% endfor %}
      </div>
      <h4 class="card-header bg-info">MESSAGES: {{chats|length}} </h4>
    </div>
    <form class="form-group">
      <label for="exampleTextarea" class="form-label mt-4"></label>
      <textarea class="form-control" id="exampleTextarea" rows="3" data-target="chat.input" placeholder="Type your message.." minlength="3"></textarea>
      <div class="d-grid gap-2">
        <button class="btn btn-lg btn-success"  data-action="click->chat#post" type="submit"> Send </button>
      </div>
      <br>
      <div class="card">
        <div class="card-body">
        <h6>Messages stored <h3>{{chats|length}}</h3></h6>
        Note, that Messages stored value is not updated at every new message arrived,
         instead you have to reload the page.
          That is because it is not in data-reflex-root="#chat-container".
        </div>
      </div>
    </form>
</article>
{% endblock %}

tutorial/templates/blog/examplereflex.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h3 class="lead"> This is simple <code>reflex</code>, it does not have <strong>javascript controller</strong>.</h3>
    <script src="{% static 'sockpuppet/sockpuppet.js' %}"></script>
    <button class="btn btn-success"
      href="#"
      data-reflex="click->ExamplereflexReflex#increment"
      data-count="{{ count }}"
    >Increment </button>
    <button class="btn btn-dark"><strong>{{ count }}</strong></button>
{% endblock content %}    

tutorial/templates/blog/examplereflex_with_js.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h3 class="lead"> This <code>Reflex</code> is compiled with webpack and it has <strong>javascript controller</strong>.</h3>
  <button class="btn btn-success"  href="#"
        data-controller="examplereflex_with_js"
        data-action="click->examplereflex_with_js#increment"
        data-count="{{ count }}"
    >Increment
  </button>
  <button class="btn btn-dark"><strong>{{ count }}</strong></button>
{% endblock content %}

tutorial/templates/blog/post_comment.html
{% load static %}

<body>
    <script type="module" src="{% static 'js/post_comment.js' %}"></script>
    <a  href="#"
        data-controller="post_comment"
        data-action="click->post_comment#increment"
        data-count="{{ count }}"
    >Increment </a><span>{{ count }}</span>
</body>

tutorial/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load comments %}
{% load comments_xtd %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
  <div class="pb-3">
    <h1 class="text-center">{{ object.title }}</h1>
    <p class="small text-center">{{ object.publish|date:"l, j F Y" }}</p>
  </div>
  <div>
    {{ object.body|linebreaks }}
  </div>
  {% get_comment_count for object as comment_count %}
  <div class="pt-4 text-center">
    <a href="{% url 'blog:post_list' %}">Back to the post list</a>
    &nbsp;&sdot;&nbsp;
    {{ comment_count }} comment{{ comment_count|pluralize }}
    ha{{ comment_count|pluralize:"s,ve" }} been posted.
  </div>

  <a  href="#"
      data-controller="post_comment"
      data-action="click->post_comment#post"
      data-count="{{ count }}"
  >Increment </a><span>{{ count }}</span>

  {% if object.allow_comments %}
    <div class="card card-block mb-5">
      <div class="card-body">
        <h4 class="card-title text-center pb-3">Post your comment</h4>
          {% render_comment_form for object %}
      </div>
    </div>
  {% endif %}
  {% if comment_count %}
    <ul class="media-list">
      {% render_xtdcomment_tree for object allow_flagging allow_feedback show_feedback %}
    </ul>
  {% endif %}
{% endblock content %}

tutorial/templates/blog/post_list.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
  <h1 class="pb-3 text-center">Blog</h1>
  <div class="row justify-content-center flex-fill">
    <div class="col-md-10">
      {% for object in object_list %}
      <h3><a class="nounderline" href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
      <p class="date">Published {{ object.publish }}</p>
      {{ object.body|truncatewords:30|linebreaks }}
        {% get_comment_count for object as comment_count %}
        <p class="date">Published {{ object.publish }}
          {% if comment_count %}
              &sdot;&nbsp;{{ comment_count }} comment{{ comment_count|pluralize }}
          {% endif %}
        </p>
      {% endfor %}
    </div>
  </div>
  <ul class="mt-5 pagination justify-content-center">
    <li class="page-item{% if not page_obj.has_previous %} disabled{% endif %}">
      <a class="page-link" href="{{ url }}?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}">previous</a>
    </li>
    {% for page_number in page_range %}
    <li class="page-item{% if page_number == page_obj.number %} active{% endif %}">
      <a class="page-link" href="{{ url }}?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endfor %}
    <li class="page-item{% if page_number == page_obj.number %} active{% endif %}">
      <a class="page-link" href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
    </li>
    <li class="page-item{% if not page_obj.has_next %} disabled{% endif %}">
      <a class="page-link" href="{{ url }}?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}">next</a>
    </li>
  </ul>
{% endblock %}

tutorial/templates/blog/search_results.html
{% extends 'base.html' %}

{% block title %}Books Search{% endblock title %}

{% block content %}
  <div class="jumbotron text-center" style="margin-bottom:0">
    <h1>Search</h1>
    <p>Click for details</p>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Post</th>
        <th scope="col">Primary Key</th>
        <th scope="col">Date</th>
        <th scope="col">Author</th>
      </tr>
    </thead>
    <tbody>
    {% for post in post_list %}
      <tr>
        <th scope="row"><h3><a class="nounderline" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3></th>
        <td>{{ post.pk }}</td>
        <td>{{ post.publish }}</td>
        <td>Anonymos</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}

tutorial/templates/blog/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  <h2>Sign up for newsletter!</h2>
  <form id="morph-form" data-reflex-root="#morph">
      {{ form|crispy }}
      <input type="submit" data-reflex="click->Signup_Reflex#add_person" class="btn btn-primary">
      <div id="morph">
          <h2>Signed:</h2>
          <table>
              <thead>
              <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Remove</th>
              </tr>
              </thead>
              <tbody>
              {% for p in people %}
                  <tr>
                      <td>{{ p.name }} </td>
                      <td>{{ p.email }}</td>
                      <td><a href="#" data-reflex="click->Signup_Reflex#remove_person"
                             data-id="{{ p.id }}">Remove</a></td>
                  </tr>
              {% endfor %}
              </tbody>
          </table>
      </div>
  </form>
{% endblock content %}

tutorial/templates/comments/400-debug.html
{% extends "base.html" %}

{% block title %}Bad request{% endblock %}

{% block content %}
<h3 class="text-center">Comment post not allowed</h3>
<p class="text-center">{{ why }}</p>
<hr/>
<p class="col-lg-offset-1 col-md-offset-1 text-muted">
  You're seeing this error because you have <code>DEBUG = True</code> in
  your Django settings file. Change that to <code>False</code>, and Django
  will display a standard 400 error page.
</p>
{% endblock %}

tutorial/templates/comments/form.html
{% load i18n %}
{% load comments %}





<form method="POST" action="{% comment_form_target %}" onsubmit="post.disabled = true; return true;"  id="morph-form" data-reflex-root="#morph">

    {% csrf_token %}
    <fieldset>
        <input type="hidden" name="next" value="{% url 'comments-xtd-sent' %}" />

        <div class="alert alert-danger" data-comment-element="errors" hidden>
        </div>

        {% for field in form %}
        {% if field.is_hidden %}<div>{{ field }}</div>{% endif %}
        {% endfor %}

        <div style="display:none">{{ form.honeypot }}</div>

        <div class="row form-group {% if 'comment' in form.errors %}has-danger{% endif %}">
            <div class="offset-md-1 col-md-10">
                {{ form.comment }}
            </div>
        </div>

        {% if not request.user.is_authenticated or not request.user.get_full_name %}
        <div class="row form-group {% if 'name' in form.errors %}has-danger{% endif %}">
            <label for="id_name" class="col-form-label col-md-3 text-right">
                {{ form.name.label }}
            </label>
            <div class="col-md-7">
                {{ form.name }}
            </div>
        </div>
        {% endif %}

        {% if not request.user.is_authenticated or not request.user.email %}
        <div class="row form-group {% if 'email' in form.errors %}has-danger{% endif %}">
            <label for="id_email" class="col-form-label col-md-3 text-right">
                {{ form.email.label }}
            </label>
            <div class="col-md-7">
                {{ form.email }}
                <span class="form-text small">{{ form.email.help_text }}</span>
            </div>
        </div>
        {% endif %}

        {% if not request.user.is_authenticated %}
        <div class="row form-group {% if 'url' in form.errors %}has-error{% endif %}">
            <label for="id_url" class="col-form-label col-md-3 text-right">
                {{ form.url.label }}
            </label>
            <div class="col-md-7">
                {{ form.url }}
            </div>
        </div>
        {% endif %}

        <div class="row form-group">
            <div class="offset-md-3 col-md-7">
                <div class="custom-control custom-checkbox">
                    {{ form.followup }}
                    <label for="id_followup{% if cid %}_{{ cid }}{% endif %}" class="custom-control-label">&nbsp;{{ form.followup.label }}</label>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="row form-group">
        <div class="offset-md-3 col-md-7">
            <input type="submit" name="post" value="{% trans 'send' %}" class="btn btn-primary" data-reflex="click->Post_Comment_Reflex#postcomment"/>
            {% if reply %}
              <button type="button" class="btn btn-danger" data-controller="post_comment" data-action="click->post_comment#post">Close</button>
            {% endif %}
        </div>
    </div>
</form>

tutorial/templates/comments/list.html
{% load i18n %}
{% load comments %}
{% load comments_xtd %}

<div id="comments" class="media-list">
  {% for comment in comment_list %}
  <div class="media pb-2">
    <a name="c{{ comment.id }}"></a>
    {{ comment.user_email|xtd_comment_gravatar }}
    <div class="media-body">
      <div class="comment pb-3">
        <h6 class="mb-1 small d-flex">
          <div class="mr-auto">{{ comment.submit_date }}&nbsp;-&nbsp;{% if comment.url and not comment.is_removed %}<a href="{{ comment.url }}" target="_new">{% endif %}{{ comment.name }}{% if comment.url %}</a>{% endif %}&nbsp;&nbsp;<a class="permalink" title="comment permalink" href="{% get_comment_permalink comment %}">¶</a></div>
        </h6>
        <div class="content">
          {% if comment.is_removed %}
          <p class="text-muted">{% trans "This comment has been removed." %}</p>
          {% else %}
          <div class="content">
            {% include "includes/django_comments_xtd/comment_content.html" with content=comment.comment %}
          </div>
          {% endif %}
          {% if comment.allow_thread and not comment.is_removed %}
          <a class="small mutedlink" href="{{ comment.get_reply_url }}">
            {% trans "Reply" %}
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

tutorial/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1 class="pb-3 text-center">Simple examples.</h1>

<div class="row justify-content-center flex-fill">
  <div class="col-md-10">
    <p class="lead">Это приложение показывает как можно использовать <strong>django-sockpuppet</strong> что бы добавить к обычному Джанго сайту <code>fully REACTIVE</code> интерфейс.</p>
    <p class="lead">This application contains examples of <strong>django-sockpuppet</strong> package implementation, which is used to create fully <strong>reactive</strong> applications without using any javascript frontend frameworks such as <code>REACT, VUE, ANGULAR</code> etc.</p>
    <p class="lead">Composed of a simple <code>blog</code> application with a <code>Post</code> model with added comments by using <strong>django-contrib-comments</strong> and <strong>django-comments-xtd</strong>.</p>
    <p class="my-3 text-center">Continue to the <a href="{% url 'blog:post_list' %}">blog</a>.</p>
  </div>
</div>

<h1 class="pb-3 text-center">Sources:</h1>
<div class="row justify-content-center flex-fill">
  <div class="col-md-10">
    <p class="lead"> <a href="#">Django-sockpuppet-expo</a> django-sockpuppet showcase.</p>
    <p class="lead"> <a href="#">Django-sockpuppet</a> Django-sockpuppet documentation.</p>
    <p class="lead"> <a href="#">StimulusReflex</a> StimulusReflex javascript library documentation.</p>
  </div>
</div>

{% endblock %}

tutorial/templates/includes/django_comments_xtd/user_feedback.html
{% if allow_feedback %}
<span class="small">

    {% if show_feedback and item.likedit_users %}
    <a class="badge badge-primary text-white cfb-counter bg-success rounded-pill" data-toggle="tooltip"
       title="{{ item.likedit_users|join:'<br/>' }}">
        {{ item.likedit_users|length }}</a>
    {% endif %}

    <a href=""
       data-reflex="click->Post_Comment_Reflex#likecomment"
       data-commentid="{{ item.comment.pk }}"
       class="{% if not item.likedit %}mutedlink{% endif %}">
        <span class="fas fa-thumbs-up fa-lg text-success"></span>
    </a>

    <span class="text-muted">|</span>

    {% if show_feedback and item.dislikedit_users %}
    <a class="badge badge-primary text-white cfb-counter bg-danger rounded-pill" data-toggle="tooltip"
       title="{{ item.dislikedit_users|join:'<br/>' }}">
        {{ item.dislikedit_users|length }}</a>
    {% endif %}

    <a href="#"
       data-reflex="click->Post_Comment_Reflex#dislikecomment"
       data-commentid="{{ item.comment.pk }}"
       class="{% if not item.dislikedit %}mutedlink{% endif %}">
        <span class="fas fa-thumbs-down fa-lg text-danger"></span>
    </a>

</span>
{% endif %}